all:
  hosts:
    local:
      ansible_connection: local
  children:
    all_zones:
      children:
        zone1:
        zone2:
    zone1:
      hosts:
        srv1:
          ansible_host: 192.168.50.101
          ansible_port: 22
        srv2:
          ansible_host: 192.168.50.102
          ansible_port: 22
    zone2:
      hosts:
        srv3:
          ansible_host: 192.168.50.103
          ansible_port: 22
        srv4:
          ansible_host: 192.168.50.104
          ansible_port: 22